# -*- coding: utf-8 -*-
"""ModelTracing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L_y960qspd3jUV30UoX439K59-mtt-Fk
"""

!git clone https://github.com/ndatkinson/CS4900_Project

# Commented out IPython magic to ensure Python compatibility.
from torch.functional import Tensor

import math
import torch
import torchvision
import torchvision.models
import torch.nn as nn
from torchvision import transforms
from PIL import Image
import tensorflow as tf
import cv2
import numpy as np
from torch.utils.mobile_optimizer import optimize_for_mobile
# %cd /content/CS4900_Project/
image = Image.open('2007_000027.jpg')
transform = transforms.Compose([
    transforms.ToTensor()
])


tensor = transform(image)
#print(tensor)
model = torch.load('unit_tgs_VOC2012.pt')
model.eval()

tensor = tensor.unsqueeze(0)

traced_script_module = torch.jit.trace(model, tensor)

optimized_traced_model = optimize_for_mobile(traced_script_module)
optimized_traced_model._save_for_lite_interpreter("model3.py")