# -*- coding: utf-8 -*-
"""standardized data testing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q1EXgziirsEf1epJr4Mla6xQGZ3alvOr
"""

import pandas as pd

data_frame = pd.DataFrame({'y': [8, 12, 15, 14, 19, 23, 25, 29],
                   'x1': [5, 7, 7, 9, 12, 9, 9, 4],
                   'x2': [11, 8, 10, 6, 6, 5, 9, 12],
                   'x3': [2, 2, 3, 2, 5, 5, 7, 9]})

data_frame

data_predictor = data_frame[['x1', 'x2', 'x3']]

data_frame[['x1', 'x2', 'x3']] = (data_predictor-data_predictor.mean())/data_predictor.std()

#standardized data
data_frame